
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.hover(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.Hover}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.signatureHelp(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.SignatureHelp}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.formatting(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.TextEdit[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.rangeFormatting(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.TextEdit[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.documentSymbol(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.SymbolInformation[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.executeCommand(System.String,System.Object[])~System.Threading.Tasks.Task{System.Object}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.execute(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.interrupt~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.reset~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.completion(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.CompletionList}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.Threading.TaskService.Run(System.Func{System.Threading.Tasks.Task},System.Threading.Tasks.Task)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.onTypeFormatting(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.TextEdit[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.resolve(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.R.LanguageServer.CompletionItem}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.didChange(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "VSTHRD200:Use \"Async\" suffix for async methods", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.R.LanguageServer.LanguageServer.didChangeConfiguration(Newtonsoft.Json.Linq.JToken,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]

